# This is a basic workflow that is manually triggered

name: Check for updates

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  schedule:
   - cron: "23 2 * * *" 
  workflow_dispatch:


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  
  check-for-updates:
    permissions:
      contents: write
    
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
    - name: Check out the repository to the runner
      uses: actions/checkout@v4  
      with:
        fetch-tags: true
        fetch-depth: 0

    - name: Show Tags
      run: git tag -l

    - name: setup github user
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

    - name: Do a release
      run: ./release.sh
      env: 
        GH_TOKEN: ${{ github.token }}
